# basic mysql docker compose
version: 1.0.0
services:
    db:
        restart: unless-stopped
        image: mysql:8.0
        environment:
            #  use empty password
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: true

        ports:
            - "3309:3306"
        volumes:
            - ./mysql:/var/lib/mysql
    db-dev:
        restart: unless-stopped
        image: mysql:8.0
        environment:
            #  use empty password
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
            - "3310:3306"
        volumes:
            - ./mysql:/var/lib/mysql