# basic mysql docker compose
version: 1.0.0
services:
    db:
        restart: unless-stopped
        image: mysql:8.0
        environment:
            #  use empty password
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: true

        ports:
            - "3309:3306"
        volumes:
            - ./mysql:/var/lib/mysql
    chrome_web:
        restart: unless-stopped
        image: selenium/standalone-chrome:114.0
        ports:
            - "4444:4444"
            - "5900:5900"
            - "9515:9515"
    